command! RSPCNew call rspc#interact#New()
command! RSPCAppend call rspc#interact#Template()
command! RSPCToggleTrace call rspc#interact#ToggleTrace()
command! RSPCMake call rspc#interact#Make()
command! RSPCFlush call rspc#interact#Flush()
command! RSPCReloadAll call rspc#interact#ReloadAll()
